**Q1. What is the distinction between a numpy array and a pandas data frame? Is there a way to convert between the two if there is?**

Using numpy, one can execute a wide variety of mathematical operations on vectors with the help of Numpy Ndarray, which offers a number of efficient and user-friendly procedures. 

Using pandas, information can be stored in memory as a two-dimensional table format called a Pandas Dataframe. One can think of it as a table with rows and columns in Excel.

In [4]:
import numpy as np
import pandas as pd

array_1 = np.random.rand(4, 3)
print("Numpy array:")
print(array_1)
  
# convert numpy array to dataframe
df = pd.DataFrame(array_1, columns =['A', 'B', 'C'])
print("\nPandas DataFrame: ")
print(df)


# convert dataframe to numpy array
print("\n Numpy array: ")
array_2 = df.to_numpy()
print(array_2)

Numpy array:
[[0.61852619 0.61123556 0.16452349]
 [0.0010475  0.34347187 0.50887136]
 [0.97105731 0.44376293 0.68671634]
 [0.05519401 0.28375364 0.14977956]]

Pandas DataFrame: 
          A         B         C
0  0.618526  0.611236  0.164523
1  0.001047  0.343472  0.508871
2  0.971057  0.443763  0.686716
3  0.055194  0.283754  0.149780

 Numpy array: 
[[0.61852619 0.61123556 0.16452349]
 [0.0010475  0.34347187 0.50887136]
 [0.97105731 0.44376293 0.68671634]
 [0.05519401 0.28375364 0.14977956]]


**Q2. What can go wrong when an user enters in a stock-ticker symbol, and how do you handle it?**

Initially, I proposed checking the HTTP status code to see if the ticker was invalid, however this is unnecessary because Bloomberg would just reroute you to a blank page if the ticker is invalid. But this website features a boilerplate notice:

The search for XYZ:India produced no matches. Try the symbol search.

**Q3. Identify some of the plotting techniques that are used to produce a stock-market chart.**



1. Bar graph
2. Line graph
3. Candle stick chart



**Q4. Why is it essential to print a legend on a stock market chart?**

The legends really make it easy to see how the data is changing in relation to the many characteristics. The programme generates coloured trends to show which characteristics are associated with particular tendencies.

**Q5. What is the best way to limit the length of a pandas data frame to less than a year?**

One can do this by specifying a beginning and an end time. In start we write the date from where we are starting and at the conclusion we put the end date. That's why one can limit it to this time frame. We can also use parameters like periods and frequencies to specify how often we need a given duration.

**Q6. What is the definition of a 180-day moving average?**

Market noise is reduced and price swings are smoothed down with the use of moving averages. A moving average is a statistical technique used to examine data points by averaging a series of subsets of the whole. When looking at a 180-day moving average, it indicates The simple moving average (SMA) is the average price over the last 180 days.

**Q7. Did the chapter&#39;s final example use &quot;indirect&quot; importing? If so, how exactly do you do it?**

Yes, it mentioned

In [5]:
from sklearn.model_selection import train_test_split as tts