**Q1. If you have any, what are your choices for increasing the comparison between different figures on the same graph?**

Matplotlib's subplots feature is a handy tool for comparing multiple data sets side-by-side on a single graph. Subplots are essentially a collection of smaller plots (where each plot forms its own axis) that can coexist in the same diagram.

**Q2. Can you explain the benefit of compound interest over a higher rate of interest that does not compound after reading this chapter?**

Because at the conclusion of each compounding period, which could be daily, monthly, quarterly, or annually, you earn returns on returns on returns, a sum of money grows at a quicker rate with compound interest than with simple interest.

**Q3. What is a histogram, exactly? Name a numpy method for creating such a graph.**

The histogram displays the sum of X values relative to Y. It means that the Y value at any given place on X is the sum of all counts or data below that X value. The built-in function numpy.histogram() is invoked.

**Q4. If necessary, how do you change the aspect ratios between the X and Y axes?**

The figure(figsize=(10,10)) method in the matplot.pyplot package can be used to shrink or enlarge the graph.

**Q5. Compare and contrast the three types of array multiplication between two numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays.**

In [2]:
import numpy as np
array_1 = np.array([[1,2,3],[4,5,6],[6,7,8]])
array_2 = np.array([[10,20,30],[40,50,60],[60,70,80]])

In [3]:
array_1 * array_2

array([[ 10,  40,  90],
       [160, 250, 360],
       [360, 490, 640]])

In [4]:
np.dot(array_1, array_2)

array([[ 270,  330,  390],
       [ 600,  750,  900],
       [ 820, 1030, 1240]])

In [5]:
np.outer(array_1, array_2)

array([[ 10,  20,  30,  40,  50,  60,  60,  70,  80],
       [ 20,  40,  60,  80, 100, 120, 120, 140, 160],
       [ 30,  60,  90, 120, 150, 180, 180, 210, 240],
       [ 40,  80, 120, 160, 200, 240, 240, 280, 320],
       [ 50, 100, 150, 200, 250, 300, 300, 350, 400],
       [ 60, 120, 180, 240, 300, 360, 360, 420, 480],
       [ 60, 120, 180, 240, 300, 360, 360, 420, 480],
       [ 70, 140, 210, 280, 350, 420, 420, 490, 560],
       [ 80, 160, 240, 320, 400, 480, 480, 560, 640]])

**Q6. Before you buy a home, which numpy function will you use to measure your monthly mortgage payment?**

**np.pmt(rate, nper, pv)** function we will be using in order to calculate monthly mortgage payment before you purchase a house.

1. rate = The periodic interest rate
2. nper = The number of payment periods
3. pv = The total value of the mortgage loan

**Q7. Can string data be stored in numpy arrays? If so, list at least one restriction that applies to this data.**

The string can be stored in an array. The maximum allowable string length is a restriction on the data type string, so this value must be taken into account whenever string data is stored.